# Generated by Django 3.1.3 on 2020-12-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201124_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_pub']},
        ),
    ]
