# Generated by Django 3.1.3 on 2020-12-03 22:20

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201203_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_body_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, db_index=True, no_rendered_field=True),
        ),
    ]
