# Generated by Django 3.1.2 on 2020-11-26 22:04

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201124_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_pub']},
        ),
        migrations.AddField(
            model_name='post',
            name='_body_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, db_index=True, no_rendered_field=True),
        ),
    ]
