# Generated by Django 3.1.3 on 2020-12-03 22:32

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201203_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_text_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
    ]
